"""Genetic algorithm search for pit-stop strategies."""

from __future__ import annotations

import os
import random
from dataclasses import dataclass
from typing import List, Sequence, Tuple

import matplotlib.pyplot as plt
import numpy as np

from config import RANDOM_SEED, get_circuit_config
from core.race_simulator import RaceSimulator
from core.strategy import Strategy


Chromosome = List[Tuple[int, str]]


@dataclass
class RankedStrategy:
    chromosome: Chromosome
    total_race_time: float
    strategy: Strategy


class GeneticStrategyOptimizer:
    """Find strong pit-stop plans using a simple genetic algorithm."""

    def __init__(
        self,
        circuit_name: str = "Silverstone",
        population_size: int = 50,
        generations: int = 100,
        elite_size: int = 5,
        mutation_rate: float = 0.15,
        tournament_size: int = 5,
        start_compound: str = "Medium",
        random_seed: int = RANDOM_SEED,
    ) -> None:
        self.circuit_name = circuit_name
        self.total_laps = int(get_circuit_config(circuit_name)["total_laps"])
        self.population_size = population_size
        self.generations = generations
        self.elite_size = elite_size
        self.mutation_rate = mutation_rate
        self.tournament_size = tournament_size
        self.start_compound = start_compound
        self.available_compounds = ["Soft", "Medium", "Hard"]
        self.random = random.Random(random_seed)

        self.population: List[Chromosome] = []
        self.history: List[float] = []
        self.best_ranked: List[RankedStrategy] = []

    def _random_chromosome(self) -> Chromosome:
        num_stops = self.random.choice([1, 2])
        pit_laps = sorted(
            self.random.sample(range(8, self.total_laps - 4), num_stops)
        )
        chromosome = [(lap, self.random.choice(self.available_compounds)) for lap in pit_laps]
        return self._repair_chromosome(chromosome)

    def _repair_chromosome(self, chromosome: Sequence[Tuple[int, str]]) -> Chromosome:
        repaired = []
        previous_lap = 4
        previous_compound = self.start_compound
        for lap, compound in sorted(chromosome, key=lambda item: item[0])[:2]:
            lap = max(previous_lap + 4, min(self.total_laps - 1, int(lap)))
            if compound == previous_compound:
                alternatives = [value for value in self.available_compounds if value != previous_compound]
                compound = self.random.choice(alternatives)
            repaired.append((lap, compound))
            previous_lap = lap
            previous_compound = compound
        return repaired

    def chromosome_to_strategy(self, chromosome: Chromosome) -> Strategy:
        name = f"GA: {self.start_compound[0]}->{'->'.join(compound[0] for _, compound in chromosome)}"
        return Strategy.from_pit_plan(
            name=name,
            start_compound=self.start_compound,
            pit_plan=chromosome,
            total_laps=self.total_laps,
            description="Generated by genetic optimizer.",
        )

    def evaluate(self, chromosome: Chromosome) -> RankedStrategy:
        strategy = self.chromosome_to_strategy(self._repair_chromosome(chromosome))
        simulator = RaceSimulator(
            strategy=strategy,
            circuit_name=self.circuit_name,
            enable_variability=False,
            enable_safety_car=False,
        )
        simulator.simulate()
        return RankedStrategy(
            chromosome=list(chromosome),
            total_race_time=float(simulator.total_race_time),
            strategy=strategy,
        )

    def _tournament_selection(self, ranked_population: Sequence[RankedStrategy]) -> Chromosome:
        competitors = self.random.sample(list(ranked_population), self.tournament_size)
        winner = min(competitors, key=lambda item: item.total_race_time)
        return list(winner.chromosome)

    def _crossover(self, parent_a: Chromosome, parent_b: Chromosome) -> tuple[Chromosome, Chromosome]:
        if not parent_a or not parent_b:
            return list(parent_a), list(parent_b)
        cut = self.random.randint(1, min(len(parent_a), len(parent_b)))
        child_a = self._repair_chromosome(list(parent_a[:cut]) + list(parent_b[cut:]))
        child_b = self._repair_chromosome(list(parent_b[:cut]) + list(parent_a[cut:]))
        return child_a, child_b

    def _mutate(self, chromosome: Chromosome) -> Chromosome:
        mutated = []
        for lap, compound in chromosome:
            new_lap = lap
            new_compound = compound
            if self.random.random() < self.mutation_rate:
                if self.random.random() < 0.5:
                    new_lap = lap + self.random.randint(-3, 3)
                else:
                    new_compound = self.random.choice(self.available_compounds)
            mutated.append((new_lap, new_compound))
        return self._repair_chromosome(mutated)

    def _initialise_population(self) -> None:
        self.population = [self._random_chromosome() for _ in range(self.population_size)]

    def run(self, verbose: bool = True, output_dir: str = "output") -> List[RankedStrategy]:
        if not self.population:
            self._initialise_population()

        for generation in range(self.generations):
            ranked_population = sorted(
                (self.evaluate(chromosome) for chromosome in self.population),
                key=lambda item: item.total_race_time,
            )
            self.history.append(ranked_population[0].total_race_time)
            if verbose:
                print(
                    f"Generation {generation + 1:03d}/{self.generations}: "
                    f"best={ranked_population[0].total_race_time:.3f}s"
                )

            next_population = [list(item.chromosome) for item in ranked_population[: self.elite_size]]
            while len(next_population) < self.population_size:
                parent_a = self._tournament_selection(ranked_population)
                parent_b = self._tournament_selection(ranked_population)
                child_a, child_b = self._crossover(parent_a, parent_b)
                next_population.append(self._mutate(child_a))
                if len(next_population) < self.population_size:
                    next_population.append(self._mutate(child_b))
            self.population = next_population

        self.best_ranked = sorted(
            (self.evaluate(chromosome) for chromosome in self.population),
            key=lambda item: item.total_race_time,
        )[:3]
        self._plot_convergence(output_dir)
        return self.best_ranked

    def _plot_convergence(self, output_dir: str) -> str:
        os.makedirs(output_dir, exist_ok=True)
        output_path = os.path.join(output_dir, "genetic_convergence.png")
        plt.figure(figsize=(10, 5))
        plt.plot(range(1, len(self.history) + 1), self.history, color="#E10600", linewidth=2.0)
        plt.title(f"Genetic Optimizer Convergence - {self.circuit_name}")
        plt.xlabel("Generation")
        plt.ylabel("Best Race Time (s)")
        plt.grid(alpha=0.3)
        plt.tight_layout()
        plt.savefig(output_path, dpi=150)
        plt.close()
        return output_path
